title: Arch Vending
description: Family-owned vending machine services for St. Louis metro and surrounding areas. Founded in 2022, we specialize in serving smaller, niche locations with quality vending solutions.
url: "https://archvending.com"
baseurl: ""

# Build settings
markdown: kramdown
permalink: pretty

# Collections
collections:
  areas:
    output: true
    permalink: /areas/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "areas"
    values:
      layout: "area"

# Navigation
navigation:
  - title: Home
    url: /
  - title: Services
    url: /services/
  - title: Service Areas
    url: /areas/
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Contact information
contact:
  phone: "(314) 555-0123"
  email: "info@archvending.com"
  address: "St. Louis, MO"

# Social media
social:
  facebook: "https://facebook.com/archvending"
  twitter: "https://twitter.com/archvending"
  linkedin: "https://linkedin.com/company/archvending"

# Colors (based on your logo)
colors:
  primary: "#123C62"    # Dark blue
  secondary: "#D4E4EC"  # Light blue
  accent: "#BE1E2D"     # Deep red
  powder: "#C5CED6"     # Powder 